stages:
  - dev
  - build
  - staging
  - prod

dev:
  stage: dev
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="develop-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/iris:develop" -t "$CI_REGISTRY/iris:$CTAG" .
    - docker push "$CI_REGISTRY/iris:develop"
    - docker push "$CI_REGISTRY/iris:$CTAG"
  only:
    - develop

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/iris:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY/iris:$CI_COMMIT_TAG"
  only:
    - tags

staging:
  stage: staging
  image: binkops.azurecr.io/tagbot:latest
  environment: staging
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/iris:$CI_COMMIT_TAG" --tag "staging"
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/iris:$CI_COMMIT_TAG" --tag "staging-$CI_COMMIT_TAG"
  only:
    - tags

prod:
  stage: prod
  image: binkops.azurecr.io/tagbot:latest
  environment: prod
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/iris:$CI_COMMIT_TAG" --tag "prod"
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/iris:$CI_COMMIT_TAG" --tag "prod-$CI_COMMIT_TAG"
  when: manual
  only:
    - tags
