stages:
  - build
  - deploy

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/iris:latest" .
    - docker push "$CI_REGISTRY/iris:latest"
  only: 
    - develop

deploy-develop:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  script:
    - kubectl config use-context dev
    - kubectl delete po $(kubectl get pods --no-headers=true -l run=iris -o custom-columns=:metadata.name)
  only:
    - develop
